### ISSUE TITLE
Discord Alerts Throwing Error

### ISSUE THREAD

**Issue by cbattlegear** [kx1t/docker-planefence#159] opened 2023-01-13 04:19 UTC
Discord alerts are currently failing with an error:

`requests.exceptions.InvalidSchema: No connection adapters were found for "['WEBHOOK_URL_HERE']"`

This seems to be an issue wiht the discord-webhooks library all up though as running discord_webhook in the container via:

`docker exec -it planefence discord_webhook -u WEBHOOK_URL_HERE -c Test`

is also throwing an identical error. 

Currently can be resolved by iterating through the list of webhook URLs and converting to tuples, then iterating through the tuples to send the alerts. I have code I will work on creating a pull request for.

**Comment by kx1t** [comment] 2023-01-17 14:21
Hi - you are absolutely right that this is caused by a change to the Discord library.

I merged in your code (and reverted the inclusion of the old Discord library to the latest in the Dockerfile) but it doesn't seem to work. Could you take a look?

Also - could you pls submit any PRs for this to the `dev` branch -- this branch has the latest code to notify to Mastodon, and as soon as the Discord notification issue is fixed, I'll PR the entire `dev` branch into `main`.

Thanks again for you help here!

**Comment by cbattlegear** [comment] 2023-01-17 18:10
Totally! Sorry I am terrible at reading docs, just went hard on fixing it locally. I will get some testing done on my side and PR it with the new discord library

**Comment by kx1t** [comment] 2023-01-17 18:44
Note that I recently added some additional files to the `dev` branch with Discord in the name -- you can totally ignore anything related to Discord that is not in Python.

**Comment by cbattlegear** [comment] 2023-01-19 04:07
Should have a fully working build in pull request #162 that resolves these issues

**Comment by kx1t** [comment] 2023-01-28 12:57
Thanks again for your help here. I had 2 fixes for this issue that I consolidated and included as part of the larger PR / release of yesterday. Should be resolved now.

**Closed** 2023-01-28 12:57 UTC
